services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}    
      